---
# box info
mint_box_name: &mint_box_name mint/dev
mint_box_url: &mint_box_url file://C:/Temp/MLOps/boxes/mint-dev.json
mint_box_version: &mint_box_version 20220311.0.0

dev_box_name: &dev_box_name kubernetes/master
dev_box_url: &dev_box_url file://C:/Temp/MLOps/boxes/kubernetes-master.json
dev_box_version: &dev_box_version 20220311.0.0

# spec
spec:
  setup:
    host_path: setup
    guest_path: /usr/local/bin/setup
  vbox:
    synced_folder:
      - disabled: false
        host_path: ~/workspace
        guest_path: /share
      - disabled: false
        host_path: .
        guest_path: /vagrant
  ssh:
    username: ubuntu
    password: ubuntu
  node_list:
    # dev
    - name: dev
      group_name: /dev-group
      enable: true
      hostname: dev.mlops
      box:
        name: *dev_box_name
        url: *dev_box_url
        version: *dev_box_version
      private_network: 192.168.56.40
      resources:
        cpus: 8
        memory: 16384
      vbguest_update: false
      disk:
        - name: dev-docker
          storagectl: SCSI
          port: 2
          size: 50
          filename: ./disks/dev-docker.vdi
          device: /dev/sdc
          mount: /var/lib/docker
      provision:
        - privileged: true
          inline: "systemctl restart docker"
        - privileged: false
          username: ubuntu
          inline: "docker"
          args: ["login", "-u", "admin", "-p", "ChangeMe!", "harbor.mlops"]
        - privileged: true
          inline: "start-jupyter.sh harbor.mlops/library/jupyter:slim /share:/home/jupyter/workspace"
    # mint
    - name: mint-dev
      group_name: /dev-group
      enable: false
      hostname: mint-dev.mlops
      box:
        name: *mint_box_name
        url: *mint_box_url
        version: *mint_box_version
      private_network: 192.168.56.41
      resources:
        cpus: 8
        memory: 8192
      vbguest_update: true
      vminfo:
        vram: 64
        monitorcount: 2
      disk:
        - name: mint-dev-docker
          storagectl: SATA
          port: 1
          size: 50
          filename: ./disks/mint-dev-docker.vdi
          device: /dev/sdb
          mount: /var/lib/docker
      provision:
        - privileged: true
          inline: "systemctl restart docker"
